PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL,
 full_name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('OWNER','ADMIN','HEADTEACHER','CLASS_TEACHER','SUBJECT_TEACHER','BURSAR','STUDENT','PARENT')),
 class_id INTEGER, subject_id INTEGER, subject TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS classes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, section TEXT DEFAULT '', academic_year TEXT NOT NULL, class_teacher_id INTEGER, UNIQUE(name,section,academic_year));
CREATE TABLE IF NOT EXISTS subjects (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, code TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS students (
 id INTEGER PRIMARY KEY AUTOINCREMENT, admission_no TEXT UNIQUE NOT NULL, index_no TEXT UNIQUE NOT NULL,
 first_name TEXT NOT NULL, middle_name TEXT DEFAULT '', last_name TEXT NOT NULL, gender TEXT, dob TEXT,
 guardian_name TEXT, guardian_phone TEXT, guardian_email TEXT, address TEXT, photo TEXT, current_class_id INTEGER,
 status TEXT DEFAULT 'ACTIVE', user_id INTEGER UNIQUE, admission_date TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admissions (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, admitted_by INTEGER NOT NULL, admission_date TEXT NOT NULL, previous_school TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS enrollments (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, class_id INTEGER NOT NULL, academic_year TEXT NOT NULL, term INTEGER NOT NULL, UNIQUE(student_id,class_id,academic_year,term));
CREATE TABLE IF NOT EXISTS scores (
 id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, subject_id INTEGER NOT NULL, class_id INTEGER NOT NULL,
 academic_year TEXT NOT NULL, term INTEGER NOT NULL, class_score REAL DEFAULT 0, exam_score REAL DEFAULT 0,
 total REAL GENERATED ALWAYS AS (class_score + exam_score) STORED, grade TEXT DEFAULT '', aggregate_points INTEGER DEFAULT 0,
 remark TEXT DEFAULT '', updated_by INTEGER, UNIQUE(student_id,subject_id,class_id,academic_year,term)
);
CREATE TABLE IF NOT EXISTS attendance (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, class_id INTEGER NOT NULL, date TEXT NOT NULL, status TEXT NOT NULL, note TEXT, UNIQUE(student_id,date));
CREATE TABLE IF NOT EXISTS fee_items (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, academic_year TEXT NOT NULL, term INTEGER NOT NULL, amount REAL NOT NULL, compulsory INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, fee_item_id INTEGER, amount REAL NOT NULL, receipt_no TEXT UNIQUE NOT NULL, paid_at TEXT NOT NULL, method TEXT DEFAULT 'CASH', received_by INTEGER, note TEXT);
CREATE TABLE IF NOT EXISTS lessons (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, subject_id INTEGER, class_id INTEGER, content TEXT, video_url TEXT, attachment_url TEXT, published INTEGER DEFAULT 0, created_by INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tests (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, subject_id INTEGER, class_id INTEGER, questions_json TEXT NOT NULL, duration_minutes INTEGER DEFAULT 30, published INTEGER DEFAULT 0, created_by INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS test_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, test_id INTEGER NOT NULL, student_id INTEGER NOT NULL, answers_json TEXT NOT NULL, score REAL DEFAULT 0, submitted_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(test_id,student_id));
CREATE TABLE IF NOT EXISTS activities (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT, date TEXT, location TEXT, created_by INTEGER);
CREATE TABLE IF NOT EXISTS announcements (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, body TEXT NOT NULL, audience TEXT DEFAULT 'ALL', published INTEGER DEFAULT 1, created_by INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS timetable (id INTEGER PRIMARY KEY AUTOINCREMENT, class_id INTEGER, subject_id INTEGER, teacher_id INTEGER, day TEXT, start_time TEXT, end_time TEXT, room TEXT);
CREATE TABLE IF NOT EXISTS sync_queue (id INTEGER PRIMARY KEY AUTOINCREMENT, device_id TEXT, operation TEXT, entity TEXT, payload_json TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, processed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, action TEXT, entity TEXT, entity_id INTEGER, detail TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
