const express=require('express'),path=require('path'),Database=require('better-sqlite3'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),crypto=require('crypto'),fs=require('fs');
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_IN_PRODUCTION';
if(process.env.NODE_ENV==='production' && JWT_SECRET==='CHANGE_THIS_SECRET_IN_PRODUCTION') throw new Error('JWT_SECRET must be set in production');
const loginAttempts=new Map();
function securityHeaders(req,res,next){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()');next()}
app.use(securityHeaders);
const DATA=path.join(__dirname,'data');if(!fs.existsSync(DATA))fs.mkdirSync(DATA,{recursive:true});
const db=new Database(path.join(DATA,'school.db'));db.pragma('foreign_keys=ON');db.exec(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8'));
app.use(express.json({limit:'12mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));
const q=(sql,...a)=>db.prepare(sql).get(...a),all=(sql,...a)=>db.prepare(sql).all(...a),run=(sql,...a)=>db.prepare(sql).run(...a);
const setting=(k,d='')=>q('SELECT value FROM settings WHERE key=?',k)?.value??d;
const currentAY=()=>setting('academic_year','2026/2027');
const currentTerm=()=>Number(setting('current_term','1'));
const setSetting=(k,v)=>run('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',k,String(v));
const tokenFor=u=>jwt.sign({id:u.id,role:u.role,username:u.username,classId:u.class_id,subjectId:u.subject_id},JWT_SECRET,{expiresIn:'12h'});
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error();req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'Authentication required'})}}
const roles=(...rs)=>(req,res,next)=>rs.includes(req.user.role)?next():res.status(403).json({error:'Access denied'});
const fail=(res,e)=>{console.error(e);res.status(400).json({error:e.message||'Request failed'})};
function audit(user,action,entity,id,detail=''){try{run('INSERT INTO audit_logs(user_id,action,entity,entity_id,detail) VALUES(?,?,?,?,?)',user?.id,action,entity,id,detail)}catch{}}
function receipt(){return 'RCPT-'+new Date().getFullYear()+'-'+crypto.randomBytes(4).toString('hex').toUpperCase()}
function balance(studentId){return all(`SELECT fi.id,fi.name,fi.amount,fi.academic_year,fi.term,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.student_id=? AND p.fee_item_id=fi.id),0) paid FROM fee_items fi WHERE fi.academic_year=? AND fi.term=?`,studentId,currentAY(),currentTerm()).reduce((s,x)=>s+Math.max(0,x.amount-x.paid),0)}
function grade(total){if(total>=80)return ['A1',1];if(total>=75)return ['B2',2];if(total>=70)return ['B3',3];if(total>=65)return ['C4',4];if(total>=60)return ['C5',5];if(total>=55)return ['C6',6];if(total>=50)return ['D7',7];if(total>=40)return ['E8',8];return ['F9',9]}
app.get('/api/public-config',(req,res)=>res.json({schoolName:setting('school_name','My School'),logo:setting('school_logo',''),motto:setting('school_motto',''),setupComplete:setting('setup_complete','0')}));
app.post('/api/setup',(req,res)=>{try{if(q("SELECT COUNT(*) c FROM users WHERE role='OWNER'").c)return res.status(409).json({error:'Owner already configured'});const {schoolName='My School',username,password,fullName='System Owner',logo=''}=req.body;if(!username||!password||password.length<6)throw Error('Username and password (6+ chars) required');const x=run('INSERT INTO users(username,password_hash,full_name,role) VALUES(?,?,?,?)',username,bcrypt.hashSync(password,12),fullName,'OWNER');setSetting('school_name',schoolName);setSetting('school_logo',logo);setSetting('setup_complete','1');setSetting('academic_year',setting('academic_year','2026/2027'));setSetting('current_term',setting('current_term','1'));setSetting('report_block_enabled','1');res.json({token:tokenFor({id:x.lastInsertRowid,role:'OWNER',username}),message:'System owner created'});audit({id:x.lastInsertRowid},'SETUP','SYSTEM',null,'Initial school setup')}catch(e){fail(res,e)}});
app.post('/api/login',(req,res)=>{try{const key=String(req.ip||'unknown');const a=loginAttempts.get(key)||{n:0,t:Date.now()};if(Date.now()-a.t>15*60*1000){a.n=0;a.t=Date.now()}if(a.n>=10)return res.status(429).json({error:'Too many login attempts. Try again later.'});const u=q('SELECT * FROM users WHERE username=? AND active=1',req.body.username);if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash)){a.n++;loginAttempts.set(key,a);return res.status(401).json({error:'Invalid username or password'});}loginAttempts.delete(key);res.json({token:tokenFor(u),user:{id:u.id,username:u.username,fullName:u.full_name,role:u.role,classId:u.class_id,subjectId:u.subject_id}})}catch(e){fail(res,e)}});
app.get('/api/health',(req,res)=>res.json({ok:true,time:new Date().toISOString(),version:'3.0'}));
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.post('/api/change-password',auth,(req,res)=>{try{const u=q('SELECT password_hash FROM users WHERE id=?',req.user.id);if(!u||!bcrypt.compareSync(req.body.currentPassword||'',u.password_hash))return res.status(400).json({error:'Current password is incorrect'});if(!req.body.newPassword||req.body.newPassword.length<8)throw Error('New password must be at least 8 characters');run('UPDATE users SET password_hash=? WHERE id=?',bcrypt.hashSync(req.body.newPassword,12),req.user.id);audit(req.user,'PASSWORD_CHANGE','USER',req.user.id);res.json({ok:true})}catch(e){fail(res,e)}});
app.get('/api/backup',auth,roles('OWNER','ADMIN'),(req,res)=>{try{db.pragma('wal_checkpoint(TRUNCATE)');const file=path.join(DATA,'school.db');res.download(file,`school-backup-${new Date().toISOString().slice(0,10)}.db`)}catch(e){fail(res,e)}});
app.get('/api/dashboard',auth,(req,res)=>{try{const students=q("SELECT COUNT(*) c FROM students WHERE status='ACTIVE'").c,classes=q('SELECT COUNT(*) c FROM classes').c,fees=q('SELECT COALESCE(SUM(amount),0) total FROM payments').total||0;const paid=q('SELECT COALESCE(SUM(amount),0) p FROM payments').p||0;const recent=all(`SELECT p.receipt_no,p.amount,p.paid_at,s.first_name||' '||s.last_name student FROM payments p JOIN students s ON s.id=p.student_id ORDER BY p.id DESC LIMIT 8`);const attendance=q("SELECT ROUND(100.0*SUM(CASE WHEN status='PRESENT' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0),1) pct FROM attendance").pct||0;const outstanding=all("SELECT s.id FROM students s WHERE s.status='ACTIVE'").reduce((sum,s)=>sum+balance(s.id),0);res.json({students,classes,fees,outstanding,attendance,recent,schoolName:setting('school_name','My School')})}catch(e){fail(res,e)}});
app.get('/api/settings',auth,(req,res)=>res.json({schoolName:setting('school_name','My School'),logo:setting('school_logo',''),motto:setting('school_motto',''),academicYear:setting('academic_year','2026/2027'),currentTerm:Number(setting('current_term','1')),reportBlockEnabled:setting('report_block_enabled','1')==='1'}));
app.post('/api/settings',auth,roles('OWNER','ADMIN'),(req,res)=>{try{for(const [k,v] of Object.entries(req.body))setSetting(k,v);audit(req.user,'UPDATE','SETTINGS',null,JSON.stringify(req.body));res.json({ok:true})}catch(e){fail(res,e)}});
app.get('/api/users',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>res.json(all(`SELECT id,username,full_name,role,class_id,subject_id,active,created_at FROM users ORDER BY full_name`)));
app.post('/api/users',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>{try{const b=req.body;if(!b.username||!b.password||!b.fullName||!b.role)throw Error('Complete all login fields');if(b.role==='OWNER'&&req.user.role!=='OWNER')throw Error('Only the owner can create another owner');const x=run('INSERT INTO users(username,password_hash,full_name,role,class_id,subject_id,subject) VALUES(?,?,?,?,?,?,?)',b.username,bcrypt.hashSync(b.password,12),b.fullName,b.role,b.classId||null,b.subjectId||null,b.subject||'');if(b.studentId)run('UPDATE students SET user_id=? WHERE id=?',x.lastInsertRowid,b.studentId);audit(req.user,'CREATE','USER',x.lastInsertRowid,b.username);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.patch('/api/users/:id',auth,roles('OWNER','ADMIN'),(req,res)=>{try{const b=req.body;if(b.password)run('UPDATE users SET password_hash=? WHERE id=?',bcrypt.hashSync(b.password,12),req.params.id);if(b.active!==undefined)run('UPDATE users SET active=? WHERE id=?',b.active?1:0,req.params.id);audit(req.user,'UPDATE','USER',req.params.id);res.json({ok:true})}catch(e){fail(res,e)}});
app.get('/api/classes',auth,(req,res)=>res.json(all(`SELECT c.*,u.full_name class_teacher FROM classes c LEFT JOIN users u ON u.id=c.class_teacher_id ORDER BY c.academic_year DESC,c.name`)));
app.post('/api/classes',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>{try{const b=req.body,x=run('INSERT INTO classes(name,section,academic_year,class_teacher_id) VALUES(?,?,?,?)',b.name,b.section||'',b.academicYear||setting('academic_year'),b.classTeacherId||null);audit(req.user,'CREATE','CLASS',x.lastInsertRowid,b.name);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.get('/api/subjects',auth,(req,res)=>res.json(all('SELECT * FROM subjects ORDER BY name')));
app.post('/api/subjects',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>{try{const x=run('INSERT INTO subjects(name,code) VALUES(?,?)',req.body.name,req.body.code||null);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.get('/api/students',auth,(req,res)=>{const qx=(req.query.q||'').trim();let rows=qx?all(`SELECT s.*,c.name class_name,c.section FROM students s LEFT JOIN classes c ON c.id=s.current_class_id WHERE s.first_name LIKE ? OR s.middle_name LIKE ? OR s.last_name LIKE ? OR s.index_no LIKE ? OR s.admission_no LIKE ? ORDER BY s.last_name`,...Array(5).fill('%'+qx+'%')):all(`SELECT s.*,c.name class_name,c.section FROM students s LEFT JOIN classes c ON c.id=s.current_class_id ORDER BY s.id DESC`);if(req.user.role==='STUDENT')rows=rows.filter(s=>s.user_id===req.user.id);res.json(rows)});
app.post('/api/students',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>{try{const b=req.body,index=b.indexNo||('NJK-'+new Date().getFullYear()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase()),admission=b.admissionNo||index;const tx=db.transaction(()=>{const x=run(`INSERT INTO students(admission_no,index_no,first_name,middle_name,last_name,gender,dob,guardian_name,guardian_phone,guardian_email,address,current_class_id,admission_date) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,admission,index,b.firstName,b.middleName||'',b.lastName,b.gender||'',b.dob||'',b.guardianName||'',b.guardianPhone||'',b.guardianEmail||'',b.address||'',b.classId||null,b.admissionDate||new Date().toISOString().slice(0,10));run('INSERT INTO admissions(student_id,admitted_by,admission_date,previous_school,notes) VALUES(?,?,?,?,?)',x.lastInsertRowid,req.user.id,b.admissionDate||new Date().toISOString().slice(0,10),b.previousSchool||'',b.notes||'');if(b.classId)run('INSERT OR IGNORE INTO enrollments(student_id,class_id,academic_year,term) VALUES(?,?,?,?)',x.lastInsertRowid,b.classId,b.academicYear||setting('academic_year'),Number(b.term||setting('current_term')));return x.lastInsertRowid});const id=tx();audit(req.user,'CREATE','STUDENT',id,`${index} ${b.firstName} ${b.lastName}`);res.json({id,indexNo:index,admissionNo:admission})}catch(e){fail(res,e)}});
app.patch('/api/students/:id',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>{try{const b=req.body;run(`UPDATE students SET first_name=?,middle_name=?,last_name=?,gender=?,dob=?,guardian_name=?,guardian_phone=?,guardian_email=?,address=?,current_class_id=?,status=? WHERE id=?`,b.firstName,b.middleName||'',b.lastName,b.gender||'',b.dob||'',b.guardianName||'',b.guardianPhone||'',b.guardianEmail||'',b.address||'',b.classId||null,b.status||'ACTIVE',req.params.id);res.json({ok:true})}catch(e){fail(res,e)}});
app.get('/api/fees/items',auth,(req,res)=>res.json(all('SELECT * FROM fee_items ORDER BY academic_year DESC,term,name')));
app.post('/api/fees/items',auth,roles('OWNER','ADMIN','HEADTEACHER','BURSAR'),(req,res)=>{try{const b=req.body,x=run('INSERT INTO fee_items(name,academic_year,term,amount,compulsory) VALUES(?,?,?,?,?)',b.name,b.academicYear||setting('academic_year'),b.term||setting('current_term'),b.amount,b.compulsory?1:0);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.get('/api/fees/student/:id',auth,(req,res)=>res.json(all(`SELECT fi.*,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.student_id=? AND p.fee_item_id=fi.id),0) paid FROM fee_items fi`,req.params.id).map(x=>({...x,balance:Math.max(0,x.amount-x.paid)}))));
app.post('/api/fees/payments',auth,roles('OWNER','ADMIN','HEADTEACHER','BURSAR'),(req,res)=>{try{const b=req.body,r=b.receiptNo||receipt(),x=run('INSERT INTO payments(student_id,fee_item_id,amount,receipt_no,paid_at,method,received_by,note) VALUES(?,?,?,?,?,?,?,?)',b.studentId,b.feeItemId||null,b.amount,r,b.paidAt||new Date().toISOString(),b.method||'CASH',req.user.id,b.note||'');audit(req.user,'CREATE','PAYMENT',x.lastInsertRowid,r);res.json({id:x.lastInsertRowid,receiptNo:r})}catch(e){fail(res,e)}});
app.get('/api/fees/receipt/:receiptNo',auth,(req,res)=>{const r=q(`SELECT p.*,s.first_name||' '||s.last_name student,s.index_no,fi.name fee_name,u.full_name received_by_name FROM payments p JOIN students s ON s.id=p.student_id LEFT JOIN fee_items fi ON fi.id=p.fee_item_id LEFT JOIN users u ON u.id=p.received_by WHERE p.receipt_no=?`,req.params.receiptNo);if(!r)return res.status(404).json({error:'Receipt not found'});res.json({...r,school:{name:setting('school_name'),logo:setting('school_logo'),motto:setting('school_motto')}})});
app.post('/api/scores',auth,roles('OWNER','ADMIN','HEADTEACHER','CLASS_TEACHER','SUBJECT_TEACHER'),(req,res)=>{try{const b=req.body,total=Number(b.classScore||0)+Number(b.examScore||0),[g,p]=grade(total);run(`INSERT INTO scores(student_id,subject_id,class_id,academic_year,term,class_score,exam_score,grade,aggregate_points,remark,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(student_id,subject_id,class_id,academic_year,term) DO UPDATE SET class_score=excluded.class_score,exam_score=excluded.exam_score,grade=excluded.grade,aggregate_points=excluded.aggregate_points,remark=excluded.remark,updated_by=excluded.updated_by`,b.studentId,b.subjectId,b.classId,b.academicYear,b.term,b.classScore||0,b.examScore||0,g,p,b.remark||'',req.user.id);res.json({ok:true,grade:g,total})}catch(e){fail(res,e)}});
app.post('/api/attendance',auth,roles('OWNER','ADMIN','HEADTEACHER','CLASS_TEACHER'),(req,res)=>{try{const b=req.body;run(`INSERT INTO attendance(student_id,class_id,date,status,note) VALUES(?,?,?,?,?) ON CONFLICT(student_id,date) DO UPDATE SET status=excluded.status,note=excluded.note,class_id=excluded.class_id`,b.studentId,b.classId,b.date,b.status,b.note||'');res.json({ok:true})}catch(e){fail(res,e)}});
app.get('/api/records/:studentId',auth,(req,res)=>{const s=q(`SELECT s.*,c.name class_name FROM students s LEFT JOIN classes c ON c.id=s.current_class_id WHERE s.id=?`,req.params.studentId);if(!s)return res.status(404).json({error:'Student not found'});if(req.user.role==='STUDENT'&&s.user_id!==req.user.id)return res.status(403).json({error:'Own records only'});res.json({student:s,scores:all(`SELECT sc.*,su.name subject,c.name class_name FROM scores sc JOIN subjects su ON su.id=sc.subject_id JOIN classes c ON c.id=sc.class_id WHERE sc.student_id=? ORDER BY sc.academic_year,sc.term,su.name`,req.params.studentId),attendance:all('SELECT * FROM attendance WHERE student_id=? ORDER BY date DESC LIMIT 200',req.params.studentId)})});
function reportData(studentId,year,term){const s=q(`SELECT s.*,c.name class_name FROM students s LEFT JOIN classes c ON c.id=s.current_class_id WHERE s.id=?`,studentId);const scores=all(`SELECT sc.*,su.name subject FROM scores sc JOIN subjects su ON su.id=sc.subject_id WHERE sc.student_id=? AND sc.academic_year=? AND sc.term=? ORDER BY su.name`,studentId,year,term);const avg=scores.length?scores.reduce((a,x)=>a+x.total,0)/scores.length:0;return {student:s,scores,average:Number(avg.toFixed(2)),school:{name:setting('school_name'),logo:setting('school_logo'),motto:setting('school_motto')},academicYear:year,term}};
function canView(req,s){return req.user.role!=='STUDENT'||s.user_id===req.user.id}
app.get('/api/report-card/:studentId',auth,(req,res)=>{const s=q('SELECT * FROM students WHERE id=?',req.params.studentId);if(!s)return res.status(404).json({error:'Student not found'});if(!canView(req,s))return res.status(403).json({error:'Own report only'});const bal=balance(s.id);if(setting('report_block_enabled','1')==='1'&&bal>0)return res.status(402).json({error:'Report card blocked until fees and levies are cleared',balance:bal});res.json(reportData(s.id,req.query.academicYear||setting('academic_year'),Number(req.query.term||setting('current_term'))))});
app.get('/api/transcript/:studentId',auth,(req,res)=>{const s=q('SELECT * FROM students WHERE id=?',req.params.studentId);if(!s)return res.status(404).json({error:'Student not found'});if(!canView(req,s))return res.status(403).json({error:'Own transcript only'});const bal=balance(s.id);if(setting('report_block_enabled','1')==='1'&&bal>0)return res.status(402).json({error:'Transcript blocked until fees and levies are cleared',balance:bal});res.json({student:s,scores:all(`SELECT sc.academic_year,sc.term,su.name subject,sc.class_score,sc.exam_score,sc.total,sc.grade,sc.remark,c.name class_name FROM scores sc JOIN subjects su ON su.id=sc.subject_id JOIN classes c ON c.id=sc.class_id WHERE sc.student_id=? ORDER BY sc.academic_year,sc.term,su.name`,s.id),school:{name:setting('school_name'),logo:setting('school_logo'),motto:setting('school_motto')}})});
app.get('/api/lessons',auth,(req,res)=>{let x=all(`SELECT l.*,s.name subject,c.name class_name FROM lessons l LEFT JOIN subjects s ON s.id=l.subject_id LEFT JOIN classes c ON c.id=l.class_id WHERE l.published=1 ORDER BY l.id DESC`);if(req.user.role==='STUDENT'){const st=q('SELECT current_class_id FROM students WHERE user_id=?',req.user.id);x=x.filter(l=>!l.class_id||!st||l.class_id===st.current_class_id)}res.json(x)});
app.post('/api/lessons',auth,roles('OWNER','ADMIN','HEADTEACHER','SUBJECT_TEACHER','CLASS_TEACHER'),(req,res)=>{try{const b=req.body,x=run('INSERT INTO lessons(title,subject_id,class_id,content,video_url,attachment_url,published,created_by) VALUES(?,?,?,?,?,?,?,?)',b.title,b.subjectId||null,b.classId||null,b.content||'',b.videoUrl||'',b.attachmentUrl||'',b.published?1:0,req.user.id);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.get('/api/tests',auth,(req,res)=>{let x=all(`SELECT t.*,s.name subject,c.name class_name FROM tests t LEFT JOIN subjects s ON s.id=t.subject_id LEFT JOIN classes c ON c.id=t.class_id WHERE t.published=1 ORDER BY t.id DESC`).map(t=>({...t,questions:JSON.parse(t.questions_json)}));if(req.user.role==='STUDENT'){const st=q('SELECT current_class_id FROM students WHERE user_id=?',req.user.id);x=x.filter(t=>!t.class_id||!st||t.class_id===st.current_class_id)}res.json(x)});
app.post('/api/tests',auth,roles('OWNER','ADMIN','HEADTEACHER','SUBJECT_TEACHER','CLASS_TEACHER'),(req,res)=>{try{const b=req.body,x=run('INSERT INTO tests(title,subject_id,class_id,questions_json,duration_minutes,published,created_by) VALUES(?,?,?,?,?,?,?)',b.title,b.subjectId||null,b.classId||null,JSON.stringify(b.questions||[]),b.durationMinutes||30,b.published?1:0,req.user.id);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.post('/api/tests/:id/submit',auth,roles('STUDENT'),(req,res)=>{try{const st=q('SELECT id FROM students WHERE user_id=?',req.user.id),t=q('SELECT * FROM tests WHERE id=? AND published=1',req.params.id);if(!st||!t)throw Error('Test unavailable');const qs=JSON.parse(t.questions_json),a=req.body.answers||[];let score=0;qs.forEach((x,i)=>{if(String(a[i]??'').trim().toLowerCase()===String(x.answer??'').trim().toLowerCase())score++});run('INSERT INTO test_attempts(test_id,student_id,answers_json,score) VALUES(?,?,?,?) ON CONFLICT(test_id,student_id) DO UPDATE SET answers_json=excluded.answers_json,score=excluded.score,submitted_at=CURRENT_TIMESTAMP',t.id,st.id,JSON.stringify(a),score);res.json({score,total:qs.length})}catch(e){fail(res,e)}});
app.get('/api/activities',auth,(req,res)=>res.json(all('SELECT * FROM activities ORDER BY date DESC,id DESC')));
app.post('/api/activities',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>{try{const b=req.body,x=run('INSERT INTO activities(title,description,date,location,created_by) VALUES(?,?,?,?,?)',b.title,b.description||'',b.date||'',b.location||'',req.user.id);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.get('/api/announcements',auth,(req,res)=>res.json(all("SELECT * FROM announcements WHERE published=1 ORDER BY id DESC LIMIT 20")));
app.post('/api/announcements',auth,roles('OWNER','ADMIN','HEADTEACHER'),(req,res)=>{try{const b=req.body,x=run('INSERT INTO announcements(title,body,audience,published,created_by) VALUES(?,?,?,?,?)',b.title,b.body,b.audience||'ALL',b.published?1:0,req.user.id);res.json({id:x.lastInsertRowid})}catch(e){fail(res,e)}});
app.get('/api/audit',auth,roles('OWNER','ADMIN'),(req,res)=>res.json(all(`SELECT a.*,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 200`)));
app.post('/api/sync',auth,(req,res)=>{try{const ops=req.body.operations||[],accepted=[];const tx=db.transaction(()=>{for(const o of ops){run('INSERT INTO sync_queue(device_id,operation,entity,payload_json) VALUES(?,?,?,?,?)',req.body.deviceId||'web',o.operation,o.entity,JSON.stringify(o.payload||{}));accepted.push(o)}});tx();res.json({accepted:accepted.length,serverTime:new Date().toISOString()})}catch(e){fail(res,e)}});
app.get('/{*splat}',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`School Management App running on http://localhost:${PORT}`));
